[workspace]

resolver = "2"

default-members = ["contract"]
members = ["contract", "integration-tests", "model"]

[workspace.dependencies]
fake = "2.9.2"
rand = "0.8.5"
anyhow = "1.0.79"
async-trait = "0.1.77"
tokio = "1.28"

integration-trait = { git = "https://github.com/sweatco/integration-utils.git", rev = "c30efebede6a3e40111c3be95e89564fe2698db1" }
integration-utils = { git = "https://github.com/sweatco/integration-utils.git", rev = "c30efebede6a3e40111c3be95e89564fe2698db1" }

model = { path = "model" }
sweat-model = { git = "https://github.com/sweatco/sweat-near", rev = "c8fc454561a74f8813a9bd8048ed661720add7c1" }
sweat-integration = { git = "https://github.com/sweatco/sweat-near", rev = "c8fc454561a74f8813a9bd8048ed661720add7c1" }

near-workspaces = "0.10.0"
near-sdk = { git = "https://github.com/sweatco/near-sdk-rs", rev = "8c48b26cc48d969c1e5f3162141fe9c824fccecd" }
near-contract-standards = { git = "https://github.com/sweatco/near-sdk-rs", rev = "8c48b26cc48d969c1e5f3162141fe9c824fccecd" }

[patch.crates-io]
near-sdk = { git = "https://github.com/sweatco/near-sdk-rs", rev = "8c48b26cc48d969c1e5f3162141fe9c824fccecd" }
