[workspace]

resolver = "2"

default-members = ["contract"]
members = ["contract", "integration-tests", "model"]

[workspace.dependencies]
fake = "2.8.0"
rand = "0.8.5"
anyhow = "1.0.75"
async-trait = "0.1.74"
tokio = "1.28"

integration-trait = { git = "https://github.com/sweatco/integration-trait.git", rev = "83a69f7ba4acab9405bf935f7dfc70f2f5279c40" }
integration-utils = { git = "https://github.com/sweatco/integration-utils.git", rev = "379029a03f092d2eb78fa0ce0cac96710749e992" }

model = { path = "model" }
sweat-model = { git = "https://github.com/sweatco/sweat-near", rev = "8a1d2824eeda0db003805c74f0a6fd1927bcda21" }
sweat-integration = { git = "https://github.com/sweatco/sweat-near", rev = "8a1d2824eeda0db003805c74f0a6fd1927bcda21" }

near-sdk = { git = "https://github.com/sweatco/near-sdk-rs", rev = "8c48b26cc48d969c1e5f3162141fe9c824fccecd" }
near-contract-standards = { git = "https://github.com/sweatco/near-sdk-rs", rev = "8c48b26cc48d969c1e5f3162141fe9c824fccecd" }
