name: Push

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Actor
        run: echo ${{ github.actor }}

      - name: Build
        run: make build-in-docker

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: sweat-claim
          path: res/sweat_claim.wasm

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: make lint

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Integration tests
        run: make integration

  push:
    needs: [ build, lint, integration-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: sweat-claim
          path: res/

      - name: Commit & Push changes
        if: ${{ github.actor != 'sweatcoin' }}
        uses: actions-js/push@master
        with:
          message: Updated binary
          branch: main
          github_token: ${{ secrets.ACTIONS_TOKEN }}
